//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalSolutionsBDM
    {
        public long Id { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public string InstanceName { get; set; }
        public Nullable<decimal> ACOseqZmed { get; set; }
        public Nullable<int> ACOseqZbest { get; set; }
        public Nullable<int> VNSslowZworst { get; set; }
        public Nullable<int> VNSslowZbest { get; set; }
        public Nullable<int> POPworst { get; set; }
        public Nullable<int> POPbest { get; set; }
        public Nullable<int> MAzWorst { get; set; }
        public Nullable<decimal> MAzMed { get; set; }
        public Nullable<int> MAzBest { get; set; }
        public Nullable<int> PBest { get; set; }
        public Nullable<int> Best { get; set; }
        public Nullable<int> UB { get; set; }
    }
}
