//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HashTest
    {
        public int Id { get; set; }
        public Nullable<int> InstanceId { get; set; }
        public Nullable<int> SampleSize { get; set; }
        public Nullable<int> UnicidadStrongHash { get; set; }
        public Nullable<int> UnicidadWeakHash { get; set; }
        public Nullable<decimal> ClientesVisitadosAvg { get; set; }
        public Nullable<int> ClientesTotal { get; set; }
        public string Decodificador { get; set; }
        public Nullable<int> BestProfit { get; set; }
    }
}
