//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        public Instance()
        {
            this.Destinies = new HashSet<Destiny>();
            this.Solutions = new HashSet<Solution>();
        }
    
        public int Id { get; set; }
        public string Author { get; set; }
        public string Set { get; set; }
        public string Name { get; set; }
        public int DestiniesCount { get; set; }
        public int Vehicles { get; set; }
        public decimal TMax { get; set; }
    
        public virtual ICollection<Destiny> Destinies { get; set; }
        public virtual ICollection<Solution> Solutions { get; set; }
    }
}
