//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOPEntities : DbContext
    {
        public TOPEntities()
            : base("name=TOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VehiclesDestiny> VehiclesDestinies { get; set; }
        public virtual DbSet<Destiny> Destinies { get; set; }
        public virtual DbSet<Instance> Instances { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<ExternalSolution> ExternalSolutions { get; set; }
    }
}
