//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverallResult
    {
        public int Id { get; set; }
        public string Metaheuristica { get; set; }
        public Nullable<int> DeltaZmin { get; set; }
        public Nullable<int> DeltaZMax { get; set; }
        public Nullable<int> DeltaZ { get; set; }
    }
}
