//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesDestiny
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int DestinyId { get; set; }
        public int Order { get; set; }
    
        public virtual Destiny Destiny { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
