//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.VehiclesDestinies = new HashSet<VehiclesDestiny>();
        }
    
        public int Id { get; set; }
        public int SolutionId { get; set; }
        public short Number { get; set; }
        public decimal TMax { get; set; }
        public decimal Distance { get; set; }
        public int SumProfit { get; set; }
        public int SolutionStep { get; set; }
        public bool IsFinalSolution { get; set; }
    
        public virtual Solution Solution { get; set; }
        public virtual ICollection<VehiclesDestiny> VehiclesDestinies { get; set; }
    }
}
